FROM golang:1.20-buster

RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
    gcc libgl1-mesa-dev xorg-dev portaudio19-dev

WORKDIR /work
COPY . .

RUN go mod download