name: Scheduled-test

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  scheduled-test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version-file: ./go.mod

    - name: Test
      run: make test
